version: "3.7"
services:
  nginx:
    image: nginx:1.15-alpine
    ports:
      - 80:80
      - 443:443
    restart: unless-stopped
    depends_on:
      - app
    volumes:
      - ./nginx-dev.conf:/etc/nginx/conf.d/default.conf
      - static_volume:/api/static
    networks:
      - config-net
  mongodb_container:
    image: mongo:latest
    environment:
      MONGO_INITDB_ROOT_USERNAME: root
      MONGO_INITDB_ROOT_PASSWORD: **********
      MONGO_INITDB_DATABASE: configuration
    ports:
      - 27017:27017
    volumes:
      - /Users/svirskasr/data/db:/data/db
      - ./mongo-init.js:/docker-entrypoint-initdb.d/mongo-init.js:ro
  app:
    #image: registry.int.janelia.org/configurator:latest
    build: ./api
    restart: unless-stopped
    volumes:
        - ./api:/api
        - static_volume:/api/static
        - /Users/svirskasr/data/informatics/data:/groups/scicompsoft/informatics/data
    depends_on:
      - mongodb_container
    environment:
      - PYTHONUNBUFFERED=1
    networks:
        - config-net

networks:
  config-net:
      driver: bridge

volumes:
  static_volume:
