version: "3.7"
services:
  nginx:
    image: nginx:1.15-alpine
    ports:
      - 80:80
      - 443:443
    restart: unless-stopped
    depends_on:
      - app
    volumes:
      - ./nginx.conf:/etc/nginx/conf.d/default.conf
      - static_volume:/api/static
      - /etc/int_cert:/etc/nginx/ssl/
    networks:
      - config-net
  app:
    image: registry.int.janelia.org/configurator:latest
    restart: unless-stopped
    volumes:
        - ./api:/api
        - static_volume:/api/static
    environment:
      - PYTHONUNBUFFERED=1
    networks:
        - config-net

networks:
  config-net:
      driver: bridge

volumes:
  static_volume:
